"""reinicio de base de datos con campo activo

Revision ID: 0339ae0542d0
Revises: 75a8ebda0c75
Create Date: 2026-04-20 20:38:34.575768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0339ae0542d0'
down_revision = '75a8ebda0c75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.drop_column('activo')

    # ### end Alembic commands ###
