"""creacion de tabla viajes

Revision ID: 1e7444aa177f
Revises: c9d9e8f02588
Create Date: 2026-04-20 18:33:48.068042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e7444aa177f'
down_revision = 'c9d9e8f02588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origen', sa.String(length=100), nullable=False),
    sa.Column('destino', sa.String(length=100), nullable=False),
    sa.Column('hora_salida', sa.String(length=20), nullable=False),
    sa.Column('asientos_disponibles', sa.Integer(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('conductor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conductor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viajes')
    # ### end Alembic commands ###
