"""Migracion a SmartCampus

Revision ID: 961aecd4bf00
Revises: 
Create Date: 2026-06-01 15:37:43.921092

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '961aecd4bf00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos_trazabilidad', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eventos_trazabilidad_accion'))
        batch_op.drop_index(batch_op.f('ix_eventos_trazabilidad_timestamp'))

    op.drop_table('eventos_trazabilidad')
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitudes_estado'))
        batch_op.drop_index(batch_op.f('unique_solicitud'))

    op.drop_table('solicitudes')
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_viajes_estado'))
        batch_op.drop_index(batch_op.f('ix_viajes_fecha_hora'))

    op.drop_table('viajes')
    op.drop_table('mensajes')
    op.drop_table('calificaciones')
    op.drop_table('reportes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reportes',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('reportante_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reportado_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('motivo', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('evidencia_url', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('estado', mysql.ENUM('pendiente', 'revisado', 'accion_tomada'), nullable=True),
    sa.Column('tipo_sancion', mysql.ENUM('ninguna', 'advertencia', 'suspension'), nullable=True),
    sa.Column('accion_tomada', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('fecha', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['reportado_id'], ['usuarios.id'], name=op.f('reportes_ibfk_2')),
    sa.ForeignKeyConstraint(['reportante_id'], ['usuarios.id'], name=op.f('reportes_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('calificaciones',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('viaje_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('autor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('destinatario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('puntuacion', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('comentario', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('fecha', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], name=op.f('calificaciones_ibfk_2')),
    sa.ForeignKeyConstraint(['destinatario_id'], ['usuarios.id'], name=op.f('calificaciones_ibfk_3')),
    sa.ForeignKeyConstraint(['viaje_id'], ['viajes.id'], name=op.f('calificaciones_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('mensajes',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('viaje_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('remitente_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('destinatario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('contenido', mysql.TEXT(), nullable=False),
    sa.Column('leido', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['destinatario_id'], ['usuarios.id'], name=op.f('mensajes_ibfk_3')),
    sa.ForeignKeyConstraint(['remitente_id'], ['usuarios.id'], name=op.f('mensajes_ibfk_2')),
    sa.ForeignKeyConstraint(['viaje_id'], ['viajes.id'], name=op.f('mensajes_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('viajes',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('conductor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('origen_zona', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('destino_zona', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('fecha_hora', mysql.DATETIME(), nullable=False),
    sa.Column('cupos_totales', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('cupos_disponibles', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('notas_reglas', mysql.TEXT(), nullable=True),
    sa.Column('estado', mysql.ENUM('abierto', 'completo', 'en_curso', 'finalizado', 'cancelado'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('origen_lat', mysql.FLOAT(), nullable=True),
    sa.Column('origen_lng', mysql.FLOAT(), nullable=True),
    sa.Column('destino_lat', mysql.FLOAT(), nullable=True),
    sa.Column('destino_lng', mysql.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['conductor_id'], ['usuarios.id'], name=op.f('viajes_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_viajes_fecha_hora'), ['fecha_hora'], unique=False)
        batch_op.create_index(batch_op.f('ix_viajes_estado'), ['estado'], unique=False)

    op.create_table('solicitudes',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('viaje_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('pasajero_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('estado', mysql.ENUM('pendiente', 'aceptada', 'rechazada', 'cancelada'), nullable=True),
    sa.Column('fecha_solicitud', mysql.DATETIME(), nullable=True),
    sa.Column('mensaje_opcional', mysql.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['pasajero_id'], ['usuarios.id'], name=op.f('solicitudes_ibfk_2')),
    sa.ForeignKeyConstraint(['viaje_id'], ['viajes.id'], name=op.f('solicitudes_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('unique_solicitud'), ['viaje_id', 'pasajero_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_solicitudes_estado'), ['estado'], unique=False)

    op.create_table('eventos_trazabilidad',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('usuario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('viaje_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('accion', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('detalles', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('eventos_trazabilidad_ibfk_1')),
    sa.ForeignKeyConstraint(['viaje_id'], ['viajes.id'], name=op.f('eventos_trazabilidad_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('eventos_trazabilidad', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eventos_trazabilidad_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_eventos_trazabilidad_accion'), ['accion'], unique=False)

    # ### end Alembic commands ###
